//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string Url { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<int> AdTypeID { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User UserProfile { get; set; }
        public virtual AdType AdType { get; set; }
    }
}
